server:
  port: 8080

logging:
  level:
    root: info
    org.hibernate: info
    org.org.springframework.web: info

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: h2db
    password: h2db
    url: jdbc:h2:mem:food_order_system_db;

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console


